# @@Let's Learn paython@@

In [2]:
print("Hello World")

Hello World


# Variables

In [6]:
x=3

In [7]:
%whos

Variable   Type    Data/Info
----------------------------
x          int     3


In [8]:
print(type(x))

<class 'int'>


In [9]:
 x=5.7

In [10]:
%whos

Variable   Type     Data/Info
-----------------------------
x          float    5.7


In [11]:
print(type(x))

<class 'float'>


In [12]:
a,b,c,d,e,f=3,4,5.6,7,8,9.76

In [14]:
abcd=1.2354

In [15]:
%whos

Variable   Type     Data/Info
-----------------------------
a          int      3
abcd       float    1.2354
b          int      4
c          float    5.6
d          int      7
e          int      8
f          float    9.76
x          float    5.7


In [16]:
del abcd

In [17]:
%whos

Variable   Type     Data/Info
-----------------------------
a          int      3
b          int      4
c          float    5.6
d          int      7
e          int      8
f          float    9.76
x          float    5.7


In [19]:
c=2+4j

In [20]:
print(type(c))

<class 'complex'>


In [21]:
s="Hello python"

In [22]:
print(type(s))

<class 'str'>


In [23]:
%whos

Variable   Type       Data/Info
-------------------------------
a          int        3
b          int        4
c          complex    (2+4j)
d          int        7
e          int        8
f          float      9.76
s          str        Hello paython
x          float      5.7


 # Operators

Note:
 +(Addition),-(Substraction),/(division),%(Mod or Remainder),* (Multiplication), //(Floor Division,10/3=3.333,10//3=3),
 ** (to the power of)

In [5]:
a=5
b=7
SumofaAndb=a+b
SubofaAndb=a-b
MultofaAndb=a*b
ModaAndb=a%b
DivisionaAndb=a/b
FloorDivisionaAndb=a//b
PoweraAndb=a**b
print('Sum',SumofaAndb)
print("Sub",SubofaAndb)
print("Multi",MultofaAndb)
print("Mod",ModaAndb)
print("division",DivisionaAndb)
print("Floor",FloorDivisionaAndb)
print("power",PoweraAndb)

Sum 12
Sub -2
Multi 35
Mod 5
division 0.7142857142857143
Floor 0
power 78125


In [42]:
s1="Hello "
s2="Python"
s=s1+s2
print(s)

Hello Python


In [43]:
10//3

3

In [44]:

10/3

3.3333333333333335

(_),underscore is default variable in python ,it will store last un assigned value

In [46]:
_

3.3333333333333335

In [49]:
t=True
f=False

In [50]:
print(t and f)
print(f and t)
print(t and t)
print(f and f)

False
False
True
False


In [51]:
print(t or f)
print(f or t)
print(t or t)
print(f or f)

True
True
True
False


In [57]:
not(t)

False

In [59]:
not((a and b) or (c or d))

False

In [61]:
(not(2!=3) and True) or (False and True)

False

In [62]:
round(5.6231)

6

In [64]:
round(4.55862,3)

4.559

In [66]:
G=divmod(26,5)

In [67]:
print(G)
type(G)

(5, 1)


tuple

In [69]:
G[0]

5

In [70]:
G[1]

1

In [72]:
isinstance(3,int)

True

In [73]:
isinstance(5.26,(int,float,str,complex))

True

In [74]:
isinstance(5.26,float)

True

In [75]:
isinstance(5+2j,(int,float,str))

False

In [76]:
isinstance(5+2j,(int,float,str,complex))

True

pow(x,y,z) x raise to the power y and remainder byz, (x ** y)%z

In [77]:
pow(3,2)

9

In [78]:
pow(3,2,2)

1

In [79]:
x=input("Enter a number")

Enter a number56


In [80]:
type(x)

str

In [81]:
x=int(x)

In [82]:
type(x)

int

In [86]:
print(x-34)

22


In [87]:
y=int(input("Enter a number"))

Enter a number33


In [88]:
x-y

23

Note:we can only concatinate strings

In [6]:
f =2
st="why"
st1="52"

In [7]:
print(f+str)


TypeError: unsupported operand type(s) for +: 'int' and 'type'

In [108]:
print(str(f)+st)

2why


In [109]:
print(str(f))

2


In [110]:
print(int(st))

ValueError: invalid literal for int() with base 10: 'why'

In [111]:
print(int(st1))

52


In [113]:
help(pow)

Help on built-in function pow in module builtins:

pow(base, exp, mod=None)
    Equivalent to base**exp with 2 arguments or base**exp % mod with 3 arguments
    
    Some types, such as ints, are able to use a more efficient algorithm when
    invoked using the three argument form.



# Condition Statements

In [6]:
a=6
b=10
if a>b:
    print("a is greater")
else:
    print("b is greater")

b is greater


In [7]:
a=10
b=12
c=3
if a>b:
    if a>c:
        print("a is greater")
    else:
        print("c is greater")
else:
    print("b is greater")
    

b is greater


In [8]:
a=10
b=8
if a>b:
    print("a is greater")
elif a==b:
    print("equal")
else:
    print("b is greater")
    
    

a is greater


Pass statement to avoid getting an error

In [9]:
a=3
b=2
if a>b:
    

IndentationError: expected an indented block (<ipython-input-9-415a2a79d397>, line 4)

In [10]:
a=3
b=2
if a>b:
    pass

# Loops 

In [11]:
i=0
while i<6:
    print(i)
    i+=1

0
1
2
3
4
5


In [12]:
i=0
while i<6:
    print(i)
    if i==3:
        break
    i+=1

0
1
2
3


In [13]:
i=0
while i<6:
    i+=1 
    if i==3:
        continue
    print(i)

1
2
4
5
6


In [14]:
arr=[1,2,3,4,5]
for x in arr:
    print(x)

1
2
3
4
5


In [15]:
for x in "srikanth":
    print(x)

s
r
i
k
a
n
t
h


In [29]:
fruits=["Ba","Ap","Or"]
for x in fruits:
    print(x)
    if x=="Ap":
        break
        
else:
    print("finished")

Ba
Ap


In [28]:
fruits=["Ba","Ap","Or"]
for x in fruits:
    if x=="Ap":
        continue
    print(x)    

Ba
Or


In [22]:
for x in range(7):
    print(x)

0
1
2
3
4
5
6


In [23]:
for x in range(4,7):
    print(x)

4
5
6


In [24]:
for x in range(1,20,2):
    print(x)

1
3
5
7
9
11
13
15
17
19


In [26]:
for x in range(4):
    print(x)
else:
    print("finished")
        

0
1
2
3
finished


In [34]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [37]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


# Functions

In Python a function is defined using the def keyword:

In [39]:
def fact(n):
    if n==0:
        return 1
    return n*fact(n-1)

fact(5)


120

In [41]:
def out(x):
    for x in x:
        print(x)
A=[1,2,3,4,5]
out(A)

1
2
3
4
5


In [42]:
def sum(a,b):
    print(a+b)
sum(2,3)

5


In [43]:
def my_function(*kids):
    print("The youngest child is " + kids[2])

my_function("Emil", "Tobias", "Linus")


The youngest child is Linus


In [44]:
def my_function(child3, child2, child1):
     print("The youngest child is " + child3)

my_function(child1 = "Emil", child2 = "Tobias", child3 = "Linus")


The youngest child is Linus


In [48]:
x=lambda a:a*10
print(x(4))


40


In [50]:
x=lambda a,b:a*b
print(x(4,3))


12


In [52]:
def fun(n):
    return lambda a:a*n
x=fun(5)
print(x(4))

20


# Lists
List items are ordered, changeable, and allow duplicate values.

In [54]:
list1=[]
list2=[1,2]
list3=[1,2,3,'A']
list4=[[1,2,'h'],[1,2,3]]
print(list1)
print(list2)
print(list3)
print(list4)

[]
[1, 2]
[1, 2, 3, 'A']
[[1, 2, 'h'], [1, 2, 3]]


In [57]:
list=['a','b','c','d']
print(list[0])
print(list[-1])
print(list[1:3])
print(list[:2])
print(list[2:])


a
d
['b', 'c']
['a', 'b']
['c', 'd']


change the list

In [61]:
n=[1,2,3,4,5]
n[0]=5
print(n)
n[1:3]=[7,8]
print(n)
n[1:3]=[5]
print(n)
n[1:3]=[9,6,3]
print(n)
n.append(12)
print(n)
n.extend([2,8,5])
print(n)
print(n+[3,4,2])
print(n*2)min

[5, 2, 3, 4, 5]
[5, 7, 8, 4, 5]
[5, 5, 4, 5]
[5, 9, 6, 3, 5]
[5, 9, 6, 3, 5, 12]
[5, 9, 6, 3, 5, 12, 2, 8, 5]
[5, 9, 6, 3, 5, 12, 2, 8, 5, 3, 4, 2]
[5, 9, 6, 3, 5, 12, 2, 8, 5, 5, 9, 6, 3, 5, 12, 2, 8, 5]


insert in list

In [68]:
m=['a','b','c']
m.insert(3,'d')
print(m)
m[4:2]=['e','f']
print(m)

['a', 'b', 'c', 'd']
['a', 'b', 'c', 'd', 'e', 'f']


delete list

In [72]:
n=[1,2,3,4,5]
del n[2]
print(n)
del n[1:2]
print(n)
n.pop(1)
print(n)
n.pop()
print(n)
n.clear()
print(n)

[1, 2, 4, 5]
[1, 4, 5]
[1, 5]
[1]
[]


In [76]:
n=[1,2,3,4,5,6,7,8,9,10]
print(len(n))
print(n[1:5])
print(n[:5])
print(n[5:])
print(n[1:5:2])
print(n[::1])
print(n[::-1])
print(n[:])


10
[2, 3, 4, 5]
[1, 2, 3, 4, 5]
[6, 7, 8, 9, 10]
[2, 4]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


# Tuples
Tuples are used to store multiple items in a single variable.
A tuple is a collection which is ordered and unchangeable.

In [31]:
mytuple1=(1,2,3,4,5)
print(mytuple1)
print(len(mytuple1))
print(hex(id(mytuple1)))
myt=(1)
myt1=(1,)
print(type(myt))
print(type(myt1))
mytuple2=(6,7,8,9)
mytuple=mytuple1+mytuple2
print(mytuple)
print(myt1*5)
m=(1,2,2,3,4,5,4,1,2)
print(m.count(2))
print(m.index(2))

(1, 2, 3, 4, 5)
5
0x240110cde50
<class 'int'>
<class 'tuple'>
(1, 2, 3, 4, 5, 6, 7, 8, 9)
(1, 1, 1, 1, 1)
3
1


# Sets
Set items are unordered, unchangeable, and do not allow duplicate values.

In [107]:
set1={1,2,3,2,4,5}
print(set1)
print(len(set1))
set2=set((4,5,6,7,8))
print(type(set2))
for x in set1:
    print(x)
set1.add(5)
print(set1)
set3={1,2,3}
set4={4,5,6}
set3.update(set4)
print(set3)
set4.discard(0)
print(set4)

{1, 2, 3, 4, 5}
5
<class 'set'>
1
2
3
4
5
{1, 2, 3, 4, 5}
{1, 2, 3, 4, 5, 6}
{4, 5, 6}


In [118]:
set1 = {"a", "b" , "c"}
set2 = {1, 2, 3}

set3 = set1.union(set2)
print(set3)
set1.update(set2)
print(set1)
x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}
x.intersection_update(y)
print(x)
z = x.intersection(y)
print(z)



{'b', 1, 2, 'a', 3, 'c'}
{'b', 1, 2, 'a', 3, 'c'}
{'apple'}
{'apple'}


In [116]:
x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}
x.symmetric_difference_update(y)
print(x)

{'cherry', 'banana', 'microsoft', 'google'}


In [117]:
x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}
z = x.symmetric_difference(y)
print(z)

{'cherry', 'banana', 'microsoft', 'google'}


# Dictonaries
Dictionaries are changeable, meaning that we can change, add or remove items after the dictionary has been created.



In [30]:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict)
x = thisdict["model"]
print(x)
x = thisdict.get("model")
print(x)
thisdict["color"] = "white"
print(thisdict)
print(thisdict.keys())
print(thisdict.values())
print(thisdict.items())
if "model" in thisdict:
    print("Yes, 'model' is one of the keys in the thisdict dictionary")
thisdict["year"] = 2020
print(thisdict)
thisdict.update({"year": 2000})
print(thisdict)
thisdict.pop("model")
print(thisdict)
for k,v in thisdict.items():
    print(k,v)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}
Mustang
Mustang
dict_keys(['brand', 'model', 'year'])
{'brand': 'Ford', 'model': 'Mustang', 'year': 1964, 'color': 'white'}
dict_values(['Ford', 'Mustang', 1964, 'white'])
dict_items([('brand', 'Ford'), ('model', 'Mustang'), ('year', 1964), ('color', 'white')])
Yes, 'model' is one of the keys in the thisdict dictionary
{'brand': 'Ford', 'model': 'Mustang', 'year': 2020, 'color': 'white'}
{'brand': 'Ford', 'model': 'Mustang', 'year': 2000, 'color': 'white'}
{'brand': 'Ford', 'year': 2000, 'color': 'white'}
brand Ford
year 2000
color white


# Pandas

In [132]:
import pandas as pd
print(pd.__version__)
mydata={
    "cars":['bmw','volto','ford'],
    "passings":[1,2,4]
  
    }

myvar=pd.DataFrame(mydata)
print(myvar)
print("********")
a=[1,2,4]
myvar1=pd.Series(a)
print(myvar1)
print("********")
print(myvar1[0])
print("********")
myvar1=pd.Series(a,index=['x','y','z'])
print(myvar1)
print("********")
print(myvar1['y'])
print("********")
cal={
    'day1':480,
    'day2':380,
    'day3':390
}
myvar=pd.Series(cal)
print(myvar)
print("********")
mydata1={
    "num":[2,4,5,3],
    "nam":['a','b','c','d']
    
}
var=pd.DataFrame(mydata1)
print(var)
print("********")
var.sort_values(by='num',ascending=True,inplace=True)
print(var)
print("********")
var['Rank']=var['num'].rank()
print(var)
print("********")
print(var.loc[var['nam'].isin(['b','d']),['num','nam']])
print("********")
print(var.iloc[0:2,[1]])
print("********")
var.drop('Rank',axis=1,inplace=True)
print(var)



1.2.4
    cars  passings
0    bmw         1
1  volto         2
2   ford         4
********
0    1
1    2
2    4
dtype: int64
********
1
********
x    1
y    2
z    4
dtype: int64
********
2
********
day1    480
day2    380
day3    390
dtype: int64
********
   num nam
0    2   a
1    4   b
2    5   c
3    3   d
********
   num nam
0    2   a
3    3   d
1    4   b
2    5   c
********
   num nam  Rank
0    2   a   1.0
3    3   d   2.0
1    4   b   3.0
2    5   c   4.0
********
   num nam
3    3   d
1    4   b
********
  nam
0   a
3   d
********
   num nam
0    2   a
3    3   d
1    4   b
2    5   c


In [135]:
import pandas as pd
from sklearn.datasets import load_iris
iris = load_iris()
print(iris)


{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [166]:
df = pd.DataFrame(iris.data,columns=iris['feature_names'])
df['Category'] = iris['target']
df


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     Category  
0           0  
1           0  
2           0  
3           0  
4           0  
..        ...  
145         2  
146         2  
147         2  
148         2  
149         2  

[150 rows x 5 columns]

In [167]:
print(df.shape )
print("*********************************")
print(df.isnull().sum())
print("*********************************")
print(df.nunique())
print("*********************************")
print(df['Category'].value_counts())
print("*********************************")
print(df.info())
print("*********************************")
print(df['sepal length (cm)'].unique())


(150, 5)
*********************************
sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
Category             0
dtype: int64
*********************************
sepal length (cm)    35
sepal width (cm)     23
petal length (cm)    43
petal width (cm)     22
Category              3
dtype: int64
*********************************
0    50
1    50
2    50
Name: Category, dtype: int64
*********************************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   Category           150 non-null    int32  
dtypes: float64(4), int32(1)
memory usage: 5.4 KB
None
*********************************
[5.1 4.9 4.7

In [168]:
print(df['sepal length (cm)'].mean())
print(df['sepal length (cm)'].median())
print(df['sepal length (cm)'].mode())
print(df['sepal length (cm)'].count())


5.843333333333334
5.8
0    5.0
dtype: float64
150


In [169]:
mapper = {0:'setosa',
         1:'versicolor',
         2:'virginica'}

# to map 0,1,2 to their neccessary categories we use the map() function

df['Category'] = df['Category'].map(mapper)
df.head()


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  Category  
0   setosa  
1   setosa  
2   setosa  
3   setosa  
4   setosa

# Numpy

In [219]:
import numpy as np
print(np.__version__)
zero = np.array(42)
one = np.array([1, 2, 3, 4, 5])
two = np.array([[1, 2, 3], [4, 5, 6]])
three = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
b1 = np.array([1, 2, 3, 4, 5],ndmin=5)
print(zero.ndim)
print(one.ndim)
print(two.ndim)
print(three.ndim)
print(b1.ndim)
print(one[0])
print(two[0,1])
print(three[0,1,2])
print(one[1:5])
print(one[1:])
print(one[:5])
print(one[1:5:2])
print(one[::2])
print(two[1, 1:2])
print(two[0:2, 1])
print(two[0:2, 1:3])
print(one.dtype)
b2 = np.array([1.1, 2.1, 3.1])
print(b2)
print(b2.dtype)
newb2 = b2.astype('i')
print(newb2)
print(newb2.dtype)
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
x[0]=25
print(arr)
print(x)
print(y)
y[1]=35
print(arr)
print(x)
print(y)
print(x.base)
print(y.base)
print(two.shape)
b3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newb3 = b3.reshape(4, 3)
print(newb3)
new1b3 = b3.reshape(2, 3, 2)
print(new1b3)
for x in one:
    print(x)
for x in two:
    for y in x:
        print(y)
for x in three:
    for y in x:
        for z in y:
            print(z)
b4 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(b4):
    print(x)
b5 = np.array([1, 2, 3])
for x in np.nditer(b5, flags=['buffered'], op_dtypes=['S']):
    print(x)
b6 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(b6[:, ::2]):
    print(x)
for idx, x in np.ndenumerate(one):
    print(idx, x)
for idx, x in np.ndenumerate(two):
    print(idx, x)
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.concatenate((arr1, arr2)))
print(np.stack((arr1, arr2)))
print(np.stack((arr1, arr2), axis=1))
print(np.hstack((arr1, arr2)))
print(np.vstack((arr1, arr2)))
print(np.dstack((arr1, arr2)))
b7 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
print(np.array_split(b7, 3))
print(np.array_split(b7, 3, axis=1))
print(np.hsplit(b7, 3))
print(np.vsplit(b7, 3))
print(np.dsplit(three, 3))
print(np.where(one==3))
print(np.searchsorted(one, 4))
print(np.searchsorted(one, 4,side='right'))
print(np.sort(one))
print(np.sort(two))
b8 = np.array([41, 42, 43, 44])
x = b8[[True, False, True, False]]
print(x)

1.20.3
0
1
2
3
5
1
2
6
[2 3 4 5]
[2 3 4 5]
[1 2 3 4 5]
[2 4]
[1 3 5]
[5]
[2 5]
[[2 3]
 [5 6]]
int32
[1.1 2.1 3.1]
float64
[1 2 3]
int32
[1 2 3 4 5]
[25  2  3  4  5]
[1 2 3 4 5]
[ 1 35  3  4  5]
[25  2  3  4  5]
[ 1 35  3  4  5]
None
[ 1 35  3  4  5]
(2, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
1
2
3
4
5
1
2
3
4
5
6
1
2
3
4
5
6
1
2
3
4
5
6
1
2
3
4
5
6
7
8
b'1'
b'2'
b'3'
1
3
5
7
(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
  

In [225]:
import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


[False, False, True, True]
[43 44]


In [226]:
import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


[False False  True  True]
[43 44]
